application: mylisticle
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /tabletop.js
  static_files: static/tabletop.js
  upload: static/tabletop.js

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

libraries:
- name: webapp2
  version: "2.5.2"
